apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rainydays
  name: rainydays-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rainydays
  type: NodePort
status:
  loadBalancer: {}
